--- 
version: "3"

networks:
  swag-public:
    external: true

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - swag-public
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - sonarr-config:/config
      - /tank/media:/media
    restart: $RESTART_POLICY

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - swag-public
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - radarr-config:/config
      - /tank/media:/media
    restart: $RESTART_POLICY

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      - swag-public
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - prowlarr-config:/config
    restart: $RESTART_POLICY

  overseerr:
    image: ghcr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - swag-public
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - overseerr-config:/config
    restart: $RESTART_POLICY

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    networks:
      - swag-public
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - nzbget-config:/config
      - /tank/media:/media
    restart: $RESTART_POLICY

volumes:
  sonarr-config:
  radarr-config:
  prowlarr-config:
  overseerr-config:
  nzbget-config:
    
      
