version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: always
    volumes:
      - ./upload:/var/www/html/storage/upload
    env_file: .env
#    ports:
#      - 80:8080
    depends_on:
      - db
    networks:
      - internal
      - swag-public
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal
networks:
  internal: {}
  swag-public:
    external: true
    
